name: magnet 

channels:
  - conda-forge # We use conda-forge, not default one.

dependencies:
  - python=3.12.*
  - pip=25.*
  
  - pip:
    - requests==2.32.3
    - aiohttp==3.11.12
    - lxml==5.2.2
    - pydantic==2.8.2
    - pytest==8.2.2
    - PyYAML==6.0.1
    - flake8==7.1.0
    - autopep8==2.3.1
    - ruff==0.5.1  
    - tqdm==4.67.0
    - pycountry==24.6.1 
    